
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mycompany.tres_direcciones.analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PAR_A = 9;
  public static final int UMINUS = 12;
  public static final int MENOS = 4;
  public static final int SUMA = 3;
  public static final int MULTIPLICACION = 5;
  public static final int EOF = 0;
  public static final int NUMERO = 2;
  public static final int DIV = 6;
  public static final int ID = 7;
  public static final int IGUAL = 8;
  public static final int error = 1;
  public static final int SEMICOLON = 11;
  public static final int PAR_C = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUMERO",
  "SUMA",
  "MENOS",
  "MULTIPLICACION",
  "DIV",
  "ID",
  "IGUAL",
  "PAR_A",
  "PAR_C",
  "SEMICOLON",
  "UMINUS"
  };
}

